apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dotnet-jenkins-1111
  janus-idp.io/tekton: dotnet-jenkins-1111
  backstage.io/kubernetes-id: dotnet-jenkins-1111
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dotnet-jenkins-1111
resources:
- deployment.yaml
- route.yaml
- service.yaml
